---
# ResourceQuota for Production Namespace
# Prod gets more resources than dev
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  labels:
    environment: production
    component: quotas
    managed-by: argocd
spec:
  hard:
    # CPU: All pods combined can REQUEST max 1.8 CPUs (leaving 0.1 for system)
    requests.cpu: "1800m"
    # CPU: All pods combined can USE max 3.8 CPUs
    limits.cpu: "3800m"
    # Memory: All pods combined can REQUEST max 3 GB (leaving 0.4 for system)
    requests.memory: 3Gi
    # Memory: All pods combined can USE max 7.5 GB
    limits.memory: "7500Mi"
    # Maximum number of pods in this namespace (node supports 17)
    pods: "16"
    # Maximum number of services
    services: "5"
---
# LimitRange for Production Namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  labels:
    environment: production
    component: limits
    managed-by: argocd
spec:
  limits:
  - type: Container
    # Maximum resources a single container can use
    max:
      cpu: "500m"
      memory: 512Mi
    # Minimum resources a single container must request
    min:
      cpu: 10m
      memory: 32Mi
    # Default resources if not specified in pod spec
    default:
      cpu: 100m
      memory: 128Mi
    # Default REQUEST resources if not specified (what the scheduler sees)
    defaultRequest:
      cpu: 10m
      memory: 32Mi
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 10m
      memory: 32Mi
