---
# ServiceAccount for developers
# This creates an identity that developers can use to interact with the cluster
# without needing full admin access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: dev-url-shortener

---
# Role defines what actions are permitted
# This Role is namespace-scoped (only applies to dev-url-shortener namespace)
# Developers can read, write, and debug resources but can't modify RBAC or cluster settings
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev-url-shortener
rules:
# Allow read/write on core Kubernetes resources
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "deployments", "jobs", "cronjobs", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Allow pod logs and exec for debugging
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["get", "create"]

# Read-only access to secrets (can inspect but not modify)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
# RoleBinding connects the ServiceAccount to the Role
# This says: "developer ServiceAccount has the permissions defined in developer Role"
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: dev-url-shortener
subjects:
- kind: ServiceAccount
  name: developer
  namespace: dev-url-shortener
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
